# =====================================================
# Docker 설치
# =====================================================
- name: "[ Docker Setup.. ]"
  hosts: docker
  become: true
  gather_facts: false

  roles:
    - docker # docker.io + compose 플러그인 설치/hold + 서비스 기동 + docker 그룹 추가
