# =====================================================
# Control Node
# =====================================================
- name: "[ Setup Control Node.. ]"
  hosts: localhost
  become: true
  gather_facts: false

  roles:
    - { role: control, tags: ['control'] }


# =====================================================
# Ubuntu Servers
# =====================================================
- name: "[ Ubuntu_Servers Settings.. ]"
  hosts: Ubuntu_Servers
  become: true
  gather_facts: false

  roles:
    - { role: root_password,         tags: ['root_password'] }
    - { role: packages,              tags: ['packages'] }
    - { role: pip_packages,          tags: ['pip_packages'] }
    - { role: nicname,               tags: ['nicname'] }
    - { role: cloud_init,            tags: ['cloud_init'] }
    - { role: ufw,                   tags: ['ufw'] }
    - { role: locale_ko,             tags: ['locale_ko'] }
    - { role: ssh_root_login,        tags: ['ssh_root_login'] }
    - { role: timezone,              tags: ['timezone'] }
    - { role: ntp,                   tags: ['ntp'] }
    - { role: open_files,            tags: ['open_files'] }
    - { role: logrotate,             tags: ['logrotate'] }
    - { role: shell_default,         tags: ['shell_default'] }
    - { role: java,                  tags: ['java'] }
    # - { role: disable_swap,        tags: ['disable_swap'] }
    - { role: enable_swap,           tags: ['enable_swap'] }
    - { role: package_version_lock,  tags: ['package_version_lock'] }
    - { role: package_update_lock,   tags: ['package_update_lock'] }
    - { role: bash_common,           tags: ['bash_common'] }
    - { role: ssh_keygen,            tags: ['ssh_keygen'] }
    - { role: etc_hosts,             tags: ['etc_hosts'] }
